### ISSUE TITLE
How to use this plugin in Eclipse neon

### ISSUE THREAD

**Issue by taochenshh** [bazelbuild/e4b#23]
I just followed the installation instructions, but cannot figure out how to use it in Eclipse neon. I don't see any difference after installing this plugin. And I cannot click `build` icon anymore after the installation. Can someone please provide a more detailed step by step instructions on how to use it? And also, the indexer in eclipse doesn't work.

**Comment by dionescu** [comment]
This plugin needs a more detailed Wiki page. The usage instructions are unclear and it took a lot of tries to understand how to configure a Bazel project.

CTTC, do you see build errors (e.g. target not found) in the console after you import a project? That would signal that you are not adding the correct targets. Here is what worked for me on Linux:
- For the project root, choose a directory so that the remaining path to sources matches the declared package path in your files (e.g. if the directory containing the Bazel WORKSPACE file is "myproject" and you keep the code under java/com/practice/e4b with a package name of com.practice.e4b) choose myproject/java as the root)
- For the target(s), select the paths to build files. You can use * to take all the targets in the BUILD file I think. The paths that worked for me were the ones that are relative to the WORKSPACE dir. So, if in the above example you have a BUILD file under java/com/practice/e4b you would add the target "java/com/practice:*".

If you still can't get it to work, look at the Bazel commands that get executed in the Console and try them from the terminal. That may be helpful to figure out the "right" paths.

If everything works correctly, after you modify a file and save it, Bazel should attempt to rebuild and let you know of any build errors.

A question for the developers: Could the plugin have an option to automatically find all the targets given the selected directories and the WORKSAPCE dir?

**Comment by damienmg** [comment]
> A question for the developers: Could the plugin have an option to automatically find all the targets given the selected directories and the WORKSAPCE dir?

You can provides '//...' this should work.

I definitely want to free a bit more of my time to work on e4b again. This is a 20% project but my work on Bazel itself has taken all my time recently. There is another 20%er that want to open-source the build editor so hopefully we can make this plugin better in the future.

**Comment by taochenshh** [comment]
sorry for the late reply. I actually wanna use this plugin to debug the .cc code of tensorflow, because right now I cannot figure out a way to debug the code in eclipse as it does not use `make`. I just noted that the plugin only works with java, so that might be the reason why I cannot see it work.

**Comment by damienmg** [comment]
@CTTC You can use ij.bazel.io with CLion if you have access to CLion

**Comment by taochenshh** [comment]
Thanks, I will try that

**Comment by taochenshh** [comment]
@damienmg Does CLion support `IntelliJ with Bazel`, I just installed that, CLion tells me that the plugin failed due to the lack of JUnit.  And I saw that CLion was not supported at least on  Oct 24 from https://github.com/bazelbuild/intellij/issues/26

**Comment by damienmg** [comment]
Oh apparently the CLion support is not yet officially done. /cc @brendandouglas

**Comment by brendandouglas** [comment]
That's right, we probably won't publish the CLion-with-Bazel plugin until there are further improvements to CLion's indexing / symbol building performance.

You can still use it (with CLion 2016.2) by building from that GitHub repo. I just tried then, from HEAD, and it all seems to work -- could you raise a separate issue in bazelbuild/intellij with the details of your JUnit problem?

For reference, I built the plugin using the command in that linked issue:
```
git fetch
git rebase origin/master
bazel build //clwb:clwb_bazel --define=ij_product=clion-latest
```
Then installed from disk in CLion.

**Comment by taochenshh** [comment]
@brendandouglas , thanks for your reply. I have ran the codes as you showed. But since there are many .jar files generated, I don't know which one to install in CLion. I have tried to install `intellij/bazel-bin/clwb/clwb_bazel_binary_deploy.jar` and `libclwb_lib.jar`, but did not succeed. Just got errors like `Fail to load plugin descriptor from file clwb_bazel_binary_deploy.jar`

**Comment by dionescu** [comment]
@CTTC: The Clion plugin worked for me. First of all, make sure you are running Clion 2016.2.2 and not Clion 2016.3. Additionally, I see that you are looking under bazel-bin and I'm not sure whether the jars there would work. IIRC, I simply added the clwb_bazel.jar that resides under bazel-genfiles/clwb via:
File->Settings->Plugins->Install plugin from disk.

**Comment by taochenshh** [comment]
Thanks, it works now. But just one more question, how can I import Bazel project like tensorflow correctly in CLion? I just read the tutorial in http://ij.bazel.io/docs/import-project.html, but I am confused at the `select project view` step. I don't know how to create .bazelproject from scratch and the root directory of tensorflow only contains an empty BUILD file. So how can I import the whole tensorflow project? Thanks.

**Comment by brendandouglas** [comment]
@CTTC you can specify targets recursively in the project view file, so one way to import tensorflow would be via this bazelproject file:

directories:
  .

targets:
  //...:all

**Comment by taochenshh** [comment]
@brendandouglas, thanks a lot for your help.
