### ISSUE TITLE
Change repo name to be bazelbuild/eclipse

### ISSUE THREAD

**Issue by steren** [bazelbuild/e4b#50]
`e4b` is a cryptic name.
We should make everything possible to make it clear that this is the Bazel Eclipse IDE plugin.
Using `eclipse` in the repo name should help.

**Comment by steren** [comment]
Also note that IntelliJ is bazelbuild/intellij
so it will make things more consistent.

**Comment by damienmg** [comment]
Sounds good to me.

**Comment by damienmg** [comment]
(side-note: can you cc me on all the bug like this one you open on the bazelbuild org, those change require similar change on the ci).

**Comment by davidzchen** [comment]
Sorry I've been out of the loop for a while.

I just saw this bug. One potential issue with naming this repo `eclipse` and the intellij plugin repo `intellij` is that people's first impression might be that this is a fork of the `eclipse` repo and that `bazelbuild/intellij` is a fork of the `intellij` repo. While the original `e4b` name might not have been descriptive enough, I think it would be better to make the repo names more descriptive to make it clear that these are plugins for Eclipse and IntelliJ and not forks of the Eclipse and IntelliJ repos themselves.

Some examples of repo names for other Eclipse plugins:

* eclipsefp - Haskell plugin for Eclipse: https://github.com/JPMoresmau/eclipsefp
* ccw (counterclockwise) - Clojure plugin for Eclipse: https://github.com/ccw-ide/ccw

And Intellij plugins:

* intellij-haskell - https://github.com/rikvdkleij/intellij-haskell
* la-clojure - https://github.com/JetBrains/la-clojure

**Comment by steren** [comment]
I was first looking for:
1. clarity: repo name must have "eclipse" in it
2. consistency: doing the same as intellij

but I agree, as discussed with Damien earlier, I also think this can be mistakenly taken for a fork of eclipse. +1 to a rename, something simple like: 'bazel-eclipse' SGTM

**Comment by damienmg** [comment]
I am fine with bazel-eclipse but it would be good if that would be the same naming for all 3 project: bazel-intellij and bazel-xcode

**Comment by damienmg** [comment]
(so in other word: I am fine with whatever make sense but waiting to see what is the consensus for all plugins names)

**Comment by davidzchen** [comment]
I am assuming you are referring to Tulsi for the xcode plugin? Since that plugin already has its own unique name, I think it is better to keep the name of that repo as `tulsi` rather than calling it `bazel-xcode`.

For the eclipse and intellij plugins, I think we should either 1) come up with unique names for them or 2) name them either bazel-eclipse/bazel-intellij or eclipse-bazel/intellij-bazel depending on what is the more common naming convention for other plugins for these editors. Based on a cursory Github one convention does not appear to be favored over the other, though using the bazel-eclipse/bazel-intellij conventions may be preferable since the bazel name comes first and there is precedence for this convention among other eclipse and intellij plugins developed by Google:

- https://github.com/GoogleCloudPlatform/google-cloud-eclipse
- https://github.com/flutter/flutter-intellij

**Comment by steren** [comment]
Re: Tulsi, we are in the process of finding it a better name.

Let's go for 2). I am opposed to cryptic codenames. I will publish a "naming your tool" guide very soon on the Bazel website giving more guidance.

**Comment by damienmg** [comment]
Let's wait until Tulsi name is decided before doing the next move.

**Comment by davidzchen** [comment]
Re: Tulsi - Understood. Let's discuss this further offline.
